### PR TITLE
#42 Element creation should respect grid snapping settings

### PR DESCRIPTION
**Pull request by tortmayr**
Introduce CreatWorkflowNodeOperationHandler that ensures that the location for create operations is snapped to the grid
Part of eclipse-glsp/glsp/issues/42

### CODE REVIEW

**Comment by tortmayr** [comment]
Good catch! While we definitively need to adapt the `WorkflowCommandPaletteActionProvider` we should also update the client side so that the last mouse position that is send to the command palette provider is already snapped accordingly (similar to  the snapping the the creation tools).

I'm wondering if it might be a good idea to introduce a central component on the server that takes care of the the snapping (basically an `ISnapper` counterpart for the server).

**Comment by martin-fleck-at** [comment]
@tortmayr I am not sure if we want to always snap all commands that the palette provides which is why I was hesitant to suggest it. It makes sense for the creation of nodes but the client is not aware of the command details. So the responsibility still must be in the server. And since the server sends "unsnapped" commands but the creation node handler fixes that, it might be ok as is for now. 

A general snapping concept might be nice but I am not sure we can/should use it universally on all command of the comman palette.

**Comment by martin-fleck-at** [comment]
@tortmayr Are you still planning on doing some work on this? If not, we probably should document the feature request for snapping (if we want it) and then we can merge this change :)

**Comment by tortmayr** [comment]
@martin-fleck-at I'm going to fix this on the server side only (like you initially proposed) and we should probably discuss the snapping feature in a separate issue.

**Comment by tortmayr** [comment]
Commands from the commandpalette and the contextmenu are now also snapped accordingly. In addition, I adjusted the existing diagram elements to ensure that all elements are on the same grid.

**Pull request merged**
